version: "3.8"

services:
  product-db:
    container_name: product-db
    image: postgres
    environment:
      POSTGRES_USER: johan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data
volumes:
  product-db-data:
    name: product-db-data